<?xml version="1.0"?>
<!-- URDF for PhantomX Pincher Kit with Global Rotation -->
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="kit">

  <!-- ============================= -->
  <!-- ðŸ”§ Global Properties -->
  <!-- ============================= -->
  <xacro:property name="PI" value="3.141592653589793" />

  <!-- ðŸ§­ Global rotation (rpy) applied to the whole model -->
  <!-- 0 0 0     â†’ normal top view
       ${PI} 0 0 â†’ upside-down bottom view -->
  <xacro:property name="global_rotation_rpy" value="0 -${PI/2} 0" />


  <!-- ============================= -->
  <!-- ðŸŽ¨ Global Material Definitions -->
  <!-- ============================= -->
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>
  <material name="yellow"><color rgba="1 1 0 1"/></material>
  <material name="green"><color rgba="0 1 0 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>
  <material name="blue"><color rgba="0 0 1 1"/></material>
  <material name="purple"><color rgba="0.5 0 0.5 1"/></material>

  <!-- ============================= -->
  <!-- ðŸ“¦ Extra STL: canastilla y soporte cÃ¡mara -->
  <!-- ============================= -->

  <!-- Pose de la canastilla respecto a baseFija_link (ajÃºstalo si queda corrido) -->
  <xacro:property name="canastilla_xyz" value="0.155 0 -0.0145" />
  <xacro:property name="canastilla_rpy" value="0 0 0" />

  <!-- Dimensiones externas (medidas desde tu STL, en metros) -->
  <xacro:property name="can_outer_x" value="0.600" />   <!-- 600 mm -->
  <xacro:property name="can_outer_y" value="0.400" />   <!-- 400 mm -->
  <xacro:property name="can_wall_h" value="0.1855" />   <!-- 185.5 mm -->
  <xacro:property name="can_wall_t" value="0.02" />     <!-- grosor paredes (2cm) -->

  <!-- Pose del soporte de cÃ¡mara respecto al robot (26 cm desde el robot).
       Asumo +X, ajusta si tu "frente" es otro eje -->
  <xacro:property name="soporte_camara_xyz" value="0.26 0 0.00" />
  <xacro:property name="soporte_camara_rpy" value="0 0 -${PI/2}" />

  <!-- ColisiÃ³n del soporte: caja 4cm x 4cm x 30cm (alto) -->
  <xacro:property name="soporte_col_size" value="0.04 0.04 0.30" />
  <!-- Centro de la caja: a 15cm en Z para que vaya de z=0 a z=0.30 -->
  <xacro:property name="soporte_col_xyz" value="0 0 0.15" />
  <xacro:property name="soporte_col_rpy" value="0 0 0" />




  <!-- ============================= -->
  <!-- ðŸ§± Robot Geometry -->
  <!-- ============================= -->
  <link name="baseFija_link">
    <visual>
      <origin xyz="0.155 0 0.000" rpy="0 0 -${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/baseElementosFijos.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0.155 0 0.0045" rpy="0 0 -${PI/2}" />
      <geometry>
        <box size="0.360 0.554 0.009" />
      </geometry>
      <material name="black" />
    </collision>
  </link>

  <link name="caseBaseRobot_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI} 0 ${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/caseBaseRobot.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
        <origin xyz="0 0 -0.024" rpy="${PI} 0 ${PI/2}" />
        <geometry>
            <box size="0.066 0.074 0.048" />
        </geometry>
        <material name="gray" />
    </collision>
  </link>

  <joint name="base_caseRobot_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="caseBaseRobot_link" />
    <origin xyz="-0.01325 0 0.054" rpy="0 0 0" />
  </joint>

  <link name="zonaRecoleccion_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI} 0 0" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/zonaCircular146mm.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 -0.003" rpy="${PI} 0 0" />
      <geometry>
        <cylinder radius="0.073" length="0.006" />
      </geometry>
      <material name="white" />
    </collision>
  </link>

  <joint name="base_zonaRecoleccion_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="zonaRecoleccion_link" />
    <origin xyz="0.096 0 0.015" rpy="0 0 0" />
  </joint>

  <link name="airpump_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 -${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/ensambleAirpump.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
      <origin xyz="-0.0647 0 0.014" rpy="${PI/2} 0 -${PI/2}" />
      <geometry>
        <box size="0.062 0.0405 0.067" />
      </geometry>
      <material name="gray" />
    </collision>
  </link>

  <joint name="base_airpump_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="airpump_link" />
    <origin xyz="0 0 0.009" rpy="0 0 0" />
  </joint>

  <link name="manijaTrasera_link">
    <visual>
      <origin xyz="0 0 0" rpy="-${PI/2} 0 ${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/manija.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
      <origin xyz="-0.010 0 0" rpy="-${PI/2} 0 ${PI/2}" />
      <geometry>
        <box size="0.136 0.0505 0.020" />
      </geometry>
      <material name="gray" />
    </collision>
  </link>

  <joint name="base_manijaTrasera_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="manijaTrasera_link" />
    <origin xyz="-0.102 0 0.03425" rpy="0 0 0" />
  </joint>

  <link name="manijaDelantera_link">
    <visual>
      <origin xyz="0 0 0" rpy="-${PI/2} 0 ${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/manija.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
      <origin xyz="-0.010 0 0" rpy="-${PI/2} 0 ${PI/2}" />
      <geometry>
        <box size="0.136 0.0505 0.020" />
      </geometry>
      <material name="gray" />
    </collision>
  </link>

  <joint name="base_manijaDelantera_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="manijaDelantera_link" />
    <origin xyz="0.432 0 0.03425" rpy="0 0 0" />
  </joint>

  <link name="canecaLateralIzquierda_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 -${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 -${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="red" />        
    </collision>
  </link>
  <joint name="base_canecaLateralIzquierda_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="canecaLateralIzquierda_link" />
    <origin xyz="-0.0135 0.12775 0.016" rpy="0 0 0" />
  </joint>


  <link name="canecaLateralDerecha_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="yellow" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${PI/2}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="yellow" />
    </collision>
  </link>
  <joint name="base_canecaLateralDerecha_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="canecaLateralDerecha_link" />
    <origin xyz="-0.0135 -0.12775 0.016" rpy="0 0 0" />
  </joint>

  <link name="canecaFrontalDerecha_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI*((180-25.5)/180)}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${PI*((180-25.5)/180)}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="blue" />
    </collision>
  </link>

  <joint name="base_canecaFrontalDerecha_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="canecaFrontalDerecha_link" />
    <origin xyz="0.19397558339 -0.09252160722 0.016" rpy="0 0 0" />
  </joint>

  <link name="canecaFrontalIzquierda_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI*(25.5/180) + PI}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="green" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${PI*(25.5/180) + PI}" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canecaGrande.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="green" />
    </collision>

  </link>


  <joint name="base_canecaFrontalIzquierda_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="canecaFrontalIzquierda_link" />
    <origin xyz="0.19397558339 0.09252160722 0.016" rpy="0 0 0" />
  </joint>


  <!-- SLT nuevos -->
  <link name="canastilla_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/canastilla.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="blue" />
    </visual>

    <!-- ColisiÃ³n: 4 paredes externas -->
    <!-- Pared frontal (+Y) -->
    <collision>
      <origin xyz="0 ${can_outer_y/2 - can_wall_t/2} ${can_wall_h/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${can_outer_x} ${can_wall_t} ${can_wall_h}"/>
      </geometry>
    </collision>

    <!-- Pared trasera (-Y) -->
    <collision>
      <origin xyz="0 -${can_outer_y/2 - can_wall_t/2} ${can_wall_h/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${can_outer_x} ${can_wall_t} ${can_wall_h}"/>
      </geometry>
    </collision>

    <!-- Pared derecha (+X) -->
    <collision>
      <origin xyz="${can_outer_x/2 - can_wall_t/2} 0 ${can_wall_h/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${can_wall_t} ${can_outer_y - 2*can_wall_t} ${can_wall_h}"/>
      </geometry>
    </collision>

    <!-- Pared izquierda (-X) -->
    <collision>
      <origin xyz="-${can_outer_x/2 - can_wall_t/2} 0 ${can_wall_h/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${can_wall_t} ${can_outer_y - 2*can_wall_t} ${can_wall_h}"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_canastilla_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="canastilla_link" />
    <origin xyz="${canastilla_xyz}" rpy="${canastilla_rpy}" />
  </joint>

  
  <link name="ensambleSoporteCamara_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://phantomx_pincher_description/meshes/STL/ensambleSoporteCamara.stl"
              scale="0.001 0.001 0.001" />
      </geometry>
      <material name="gray" />
    </visual>

    <!-- ColisiÃ³n simplificada -->
    <collision>
      <origin xyz="${soporte_col_xyz}" rpy="${soporte_col_rpy}" />
      <geometry>
        <box size="${soporte_col_size}" />
      </geometry>
    </collision>
  </link>

  <joint name="base_ensambleSoporteCamara_joint" type="fixed">
    <parent link="baseFija_link" />
    <child link="ensambleSoporteCamara_link" />
    <origin xyz="${soporte_camara_xyz}" rpy="${soporte_camara_rpy}" />
  </joint>




  <!-- ============================= -->
  <!-- ðŸŒ Global Rotation Wrapper -->
  <!-- ============================= -->
  <link name="world_link"/>

  <joint name="world_to_base_joint" type="fixed">
    <parent link="world_link"/>
    <child link="baseFija_link"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>
  <!-- 
Superior (normal)	0 0 0
Inferior (desde abajo)	${PI} 0 0
Frontal	0 -${PI/2} 0
Trasera	0 ${PI/2} 0
Lateral derecha	0 0 -${PI/2}
Lateral izquierda	0 0 ${PI/2}
  -->

</robot>
